from Infrastructure.repo import DepartmentRepository
from domain.department import Department
from domain.patient import Patient


def data_examples():
    repo = DepartmentRepository()
    p1 = Patient("Maria", "Popescu", 2760321057060, "disease")
    p2 = Patient("Amalia", "Postolache", 6030405060708 ,"fever")
    p3 = Patient("Cosmin","Pop" ,2803377263546, "covid")
    p4 = Patient("Oana","Popa" , 6020304050607, "gastr")
    p5 = Patient("Ioana", "Man", 6072716346278,"d")
    p6 = Patient("Ale","Gal" , 1661234567899, "fracture")
    d = Department(12,"department1",9,[])
    d.addPatient(p1)
    d.addPatient(p2)
    d.addPatient(p3)
    d1 = Department(44,"neurology",17,[])
    d1.addPatient(p4)
    d2 = Department(23,"surgery",10,[])
    d2.addPatient(p5)
    d2.addPatient(p6)
    repo.addDepartments(d)
    repo.addDepartments(d1)
    repo.addDepartments(d2)
    print("This is the list of departments: ")
    print(repo)
    print("This is the department at index 0:")
    print(repo.getDepartmentByIndex(0))
    print("\t")
    repo.deleteDepartmentByIndex(2)
    print("Department at index 2 has been deleted")
    print(repo)
    print("\t")
    #repo.updateDepartmentByIndex(1,222,"surgery",[])
    print("Department at index 1 has been updated")
    print(repo)
    print("\t")
    repo.sortPatByCNPGivenIndex(0)
    print("Patients in department index 0 have been sorted by personal numerical code")
    print(repo)
    print("\t")
    repo.sortDepByNoPatients()
    print("Departments have been sorted by no of patients")
    print(repo)
    print("\t")
    repo.sortDepByPatientsLimit(21)
    print("Departments have been sorted by the number of patients having the age above 21")
    print(repo)
    print("\t")
    repo.sortDepByNoPatients()
    repo.sortPatientsByFirstName()
    repo.sortPatientsByLastName()
    print("Departments have been sorted by the number of patients and the patients in a department alphabetically")
    print(repo)
    print("\t")
    print("This is the list of departments with patients under 21: ")
    deps = repo.mySearchByAge(21)
    for dep in deps:
        print(dep)
    print("\t")
    print("Patients from neurology for which the first name or last name contain a given string:")
    lst = repo.mySearchGivenString(1,"Pop")
    for el in lst:
        print(el)
    print("\t")
    print("Departments where there are patients with first name Maria: ")
    lst1 = repo.searchByFirstName("Maria")
    for elem in lst1:
        print(elem)
data_examples()